=== basehub/sectools/config/xsd/debugpolicy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.qualcomm.com/debugpolicy"
	xmlns:tns="http://www.qualcomm.com/debugpolicy">

    <element name="debugpolicy">
    	<complexType>
    		<sequence>
    			<element name="metadata" type="tns:metadata" maxOccurs="1" minOccurs="1"></element>
    			<element name="file_properties" type="tns:complex_file_properties" maxOccurs="1" minOccurs="1"></element>
    		</sequence>
    	</complexType></element>

    <complexType name="metadata">
    	<sequence>
    		<element name="chipset" type="string"></element>
    		<element name="version" type="string"></element>
    	</sequence>
    </complexType>

    <complexType name="complex_file_properties">
        <all>
        	<element name="revision" maxOccurs="1" minOccurs="1" type="unsignedInt">

        	</element>
        	<element name="serial_number_start" maxOccurs="1"
        		minOccurs="0" type="unsignedInt">
        	</element>
        	<element name="serial_number_end" maxOccurs="1"
        		minOccurs="0" type="unsignedInt">
        	</element>
        	
        	<element name="flags" type="tns:complex_flags" />
        	<element name="image_bit_map" maxOccurs="1" minOccurs="0" type="tns:complex_image_bit_map" />
        	<element name="image_id_list" maxOccurs="1" minOccurs="0" type="tns:complex_image_id_list" />
            <element name="root_cert_hash_list" type="tns:complex_root_cert_hash_list" />
            <element name="serial_num_list" maxOccurs="1" minOccurs="0" type="tns:complex_serial_num_list"/>
            <element name="root_cert_hash_qc_list" maxOccurs="1" minOccurs="0" type="tns:complex_root_cert_hash_qc_list" />
            <element name="elf" type="tns:complex_elf" />
        </all>
    </complexType>

    <complexType name="complex_flags">
        <sequence>
            <element name="flag" maxOccurs="64" minOccurs="0">
            	<complexType>
    				<all>
                        <element name="bit_pos" type="int" />
                        <element name="value" type="boolean"/>
    				</all>
            	</complexType>
            </element>
        </sequence>
    </complexType>
    
    <complexType name="complex_image_bit_map">
        <sequence>
            <element name="swid" maxOccurs="32" minOccurs="0">
            	<complexType>
    				<all>
                        <element name="bit_pos" type="int" />
                        <element name="value" type="boolean"/>
    				</all>
            	</complexType>
            </element>
        </sequence>
    </complexType>

    <complexType name="complex_image_id_list">
        <sequence>
            <element name="image_id" maxOccurs="32" minOccurs="0" type="string">
            </element>
        </sequence>
    </complexType>

    <complexType name="complex_root_cert_hash_list">
        <sequence>
            <element name="root_cert_hash" maxOccurs="4"
            	minOccurs="0" type="string">
            </element>
        </sequence>
    </complexType>

    <complexType name="complex_serial_num_list">
        <sequence>
            <element name="serial_num" maxOccurs="200"
            	minOccurs="1" type="string">
            </element>
        </sequence>
    </complexType>
    
    <complexType name="complex_root_cert_hash_qc_list">
        <sequence>
            <element name="root_cert_hash_qc" maxOccurs="4"
            	minOccurs="0" type="string">
            </element>
        </sequence>
    </complexType>
    
	<complexType name="complex_elf">
        <all>
        	<element name="elf_class" type="unsignedInt" maxOccurs="1" minOccurs="1"/>
        	<element name="phys_addr" type="string">
        	</element>
        </all>
    </complexType>

</schema>

=== basehub/sectools/config/9x40/9x40_debugpolicy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
===============================================================================

  Copyright (c) 2013-2016 Qualcomm Technologies, Inc.
  All Rights Reserved.
  Confidential and Proprietary - Qualcomm Technologies, Inc.

===============================================================================
-->

<tns:debugpolicy xmlns:tns="http://www.qualcomm.com/debugpolicy"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.qualcomm.com/debugpolicy ../xsd/debugpolicy.xsd">

    <metadata>
        <chipset>9x40</chipset>
        <version>1.0</version>
    </metadata>

    <file_properties>
        <revision>2</revision> <!--DebugPolicy V2-->

        <flags>
            <flag> <bit_pos>0</bit_pos> <value>0</value> </flag> <!--DP_ENABLE_ONLINE_CRASH_DUMPS-->
            <flag> <bit_pos>1</bit_pos> <value>0</value> </flag> <!--DP_ENABLE_OFFLINE_CRASH_DUMPS-->
            <flag> <bit_pos>2</bit_pos> <value>0</value> </flag> <!--DP_ENABLE_JTAG-->
            <flag> <bit_pos>3</bit_pos> <value>0</value> </flag> <!--DP_ENABLE_LOGS-->
        </flags>

        <image_bit_map> <!--Range: 0 to 32-->
            <swid> <bit_pos>0</bit_pos> <value>0</value> </swid> <!--XBL-->
            <swid> <bit_pos>1</bit_pos> <value>0</value> </swid> <!--MBA-->
            <swid> <bit_pos>2</bit_pos> <value>0</value> </swid> <!--AMSS_HASH_TABLE-->
        </image_bit_map>

        <root_cert_hash_list> <!--Range: 0 to 4-->
            <root_cert_hash>0000000000000000000000000000000000000000000000000000000000000000</root_cert_hash>
        </root_cert_hash_list>

        <serial_num_list> <!--Range: 1 to 200-->
            <serial_num>00000000</serial_num>
        </serial_num_list>

        <elf>
            <elf_class>32</elf_class> <!--Elf: 32 or 64-->
            <phys_addr>817FA000</phys_addr> <!--9x40 - Debugpolicy Physical Address-->
        </elf>
    </file_properties>
</tns:debugpolicy>

=== basehub/sectools/config/8994/8994_debugpolicy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
===============================================================================

  Copyright (c) 2013-2016 Qualcomm Technologies, Inc.
  All Rights Reserved.
  Confidential and Proprietary - Qualcomm Technologies, Inc.

===============================================================================
-->

<tns:debugpolicy xmlns:tns="http://www.qualcomm.com/debugpolicy"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.qualcomm.com/debugpolicy ../xsd/debugpolicy.xsd">

    <metadata>
        <chipset>8994</chipset>
        <version>1.0</version>
    </metadata>

    <file_properties>
        <revision>1</revision>

        <serial_number_start>0</serial_number_start>
        <serial_number_end>0</serial_number_end>

        <flags>
            <flag> <bit_pos>0</bit_pos> <value>0</value> </flag>
            <flag> <bit_pos>1</bit_pos> <value>0</value> </flag>
            <flag> <bit_pos>2</bit_pos> <value>0</value> </flag>
            <flag> <bit_pos>3</bit_pos> <value>0</value> </flag>
            <flag> <bit_pos>4</bit_pos> <value>0</value> </flag>
        </flags>

        <image_id_list>
            <image_id>0</image_id>
        </image_id_list>

        <root_cert_hash_list>
            <root_cert_hash>0000000000000000000000000000000000000000000000000000000000000000</root_cert_hash>
        </root_cert_hash_list>

        <elf>
            <elf_class>32</elf_class>
            <phys_addr>06D11000</phys_addr>
        </elf>
    </file_properties>
</tns:debugpolicy>
